const AUTO_UPDATE_PLAYER_LOAD_STATUS = Symbol('AUTO_UPDATE_PLAYER_LOAD_STATUS')
const AUTO_UPDATE_PLAYER_DURATION = Symbol('AUTO_UPDATE_PLAYER_DURATION')
const USER_SET_PLAYER_CURSOR = Symbol('USER_SET_PLAYER_CURSOR')
const SET_PLAYER_REFERENCE = Symbol('SET_PLAYER_REFERENCE')
const SET_PLAYER_PLAYING_STATE = Symbol('SET_PLAYER_PLAYING_STATE')
const SET_VOLUME_LEVEL = Symbol('SET_VOLUME_LEVEL')

export {
  AUTO_UPDATE_PLAYER_LOAD_STATUS,
  AUTO_UPDATE_PLAYER_DURATION,
  USER_SET_PLAYER_CURSOR,
  SET_PLAYER_PLAYING_STATE,
  SET_PLAYER_REFERENCE,
  SET_VOLUME_LEVEL
}