const AUTO_UPDATE_PLAYER_LOAD_STATUS = 'AUTO_UPDATE_PLAYER_LOAD_STATUS'
const AUTO_UPDATE_PLAYER_DURATION = 'AUTO_UPDATE_PLAYER_DURATION'
const USER_SET_PLAYER_CURSOR = 'USER_SET_PLAYER_CURSOR'
const SET_PLAYER_PLAYING_STATE = 'SET_PLAYER_PLAYING_STATE'
const SET_VOLUME_LEVEL = 'SET_VOLUME_LEVEL'
const VIDEO_LOAD_URL = 'VIDEO_LOAD_URL'
const VIDEO_CLEAR = 'VIDEO_CLEAR'

export {
  AUTO_UPDATE_PLAYER_LOAD_STATUS,
  AUTO_UPDATE_PLAYER_DURATION,
  USER_SET_PLAYER_CURSOR,
  SET_PLAYER_PLAYING_STATE,
  SET_VOLUME_LEVEL,
  VIDEO_LOAD_URL,
  VIDEO_CLEAR
}