const WIN_UPDATE_PERIOD = 400
const MEDIA_NODE_RECONNECT_AFTER_S = 10
const MEDIA_NODE_APP_NAME = 'colab2'
const VERSION = '0.5'
const SECONDS_BETWEEN_TIME_LINE_UPDATED = 1
const VIDEO_PROGRESS_UPDATE_FREQUENCY = 500
const TOPBAR_BASE_HEIGHT = 64
const TOPBAR_BOTTOM_BORDER_WIDTH = 2

export {
  WIN_UPDATE_PERIOD,
  MEDIA_NODE_RECONNECT_AFTER_S,
  MEDIA_NODE_APP_NAME,
  SECONDS_BETWEEN_TIME_LINE_UPDATED,
  VERSION,
  VIDEO_PROGRESS_UPDATE_FREQUENCY,
  TOPBAR_BASE_HEIGHT,
  TOPBAR_BOTTOM_BORDER_WIDTH
}
