const WIN_UPDATE_PERIOD = 400
const MEDIA_NODE_RECONNECT_AFTER_S = 10
const MEDIA_NODE_APP_NAME = 'colab2'
const VERSION = '0.5'

export {
  WIN_UPDATE_PERIOD,
  MEDIA_NODE_RECONNECT_AFTER_S,
  MEDIA_NODE_APP_NAME,
  VERSION
}