const AUTH = Symbol('MEDIA_NODE_AUTH')
const AUTH_FAIL = Symbol('MEDIA_NODE_AUTH_FAIL')
const AUTH_OK = Symbol('MEDIA_NODE_AUTH_OK')
const REQUEST_AUTO_AUTH = Symbol('MEDIA_NODE_REQUEST_AUTO_AUTH')
const RESET = Symbol('MEDIA_NODE_RESET')
const INVALIDATE_AUTH = Symbol('INVALIDATE_AUTH')

export { RESET, AUTH, REQUEST_AUTO_AUTH, AUTH_FAIL, AUTH_OK, INVALIDATE_AUTH }
