const AUTH = 'MEDIA_NODE_AUTH'
const AUTH_FAIL = 'MEDIA_NODE_AUTH_FAIL'
const AUTH_OK = 'MEDIA_NODE_AUTH_OK'
const REQUEST_AUTO_AUTH = 'MEDIA_NODE_REQUEST_AUTO_AUTH'
const RESET = 'MEDIA_NODE_RESET'
const INVALIDATE_AUTH = 'INVALIDATE_AUTH'

export { RESET, AUTH, REQUEST_AUTO_AUTH, AUTH_FAIL, AUTH_OK, INVALIDATE_AUTH }
