const DASHBOARD_SELECT_PROJECT = 'DASHBOARD_SELECT_PROJECT'
const DASHBOARD_FETCH_OWN_PROJECTS = 'DASHBOARD_FETCH_OWN_PROJECTS'
const DASHBOARD_SET_EXPS_FILTER = 'DASHBOARD_SET_EXPS_FILTER'

export {
  DASHBOARD_SELECT_PROJECT,
  DASHBOARD_FETCH_OWN_PROJECTS,
  DASHBOARD_SET_EXPS_FILTER
}
