const DASHBOARD_SELECT_PROJECT = Symbol('DASHBOARD_SELECT_PROJECT')
const DASHBOARD_FETCH_OWN_PROJECTS = Symbol('DASHBOARD_FETCH_OWN_PROJECTS')
const DASHBOARD_SET_EXPS_FILTER = Symbol('DASHBOARD_SET_EXPS_FILTER')

export {
  DASHBOARD_SELECT_PROJECT,
  DASHBOARD_FETCH_OWN_PROJECTS,
  DASHBOARD_SET_EXPS_FILTER
}
