const WINDOW_WIDTH_UPDATE = 'WINDOW_WIDTH_UPDATE'
const WINDOW_HEIGHT_UPDATE = 'WINDOW_HEIGHT_UPDATE'
const TOPBAR_HEIGHT_UPDATE = 'TOPBAR_HEIGHT_UPDATE'
const START_MEDIA_NODE_AUTH = 'START_MEDIA_NODE_AUTH'
const NOTIFY_SUBSCRIPTION_READY = 'NOTIFY_SUBSCRIPTION_READY'

export {
  WINDOW_HEIGHT_UPDATE,
  WINDOW_WIDTH_UPDATE,
  TOPBAR_HEIGHT_UPDATE,
  START_MEDIA_NODE_AUTH,
  NOTIFY_SUBSCRIPTION_READY
}
