const WINDOW_WIDTH_UPDATE = Symbol('WINDOW_WIDTH_UPDATE')
const WINDOW_HEIGHT_UPDATE = Symbol('WINDOW_HEIGHT_UPDATE')
const START_MEDIA_NODE_AUTH = Symbol('START_MEDIA_NODE_AUTH')
const NOTIFY_SUBSCRIPTION_READY = Symbol('NOTIFY_SUBSCRIPTION_READY')
export {
  WINDOW_HEIGHT_UPDATE,
  WINDOW_WIDTH_UPDATE,
  START_MEDIA_NODE_AUTH,
  NOTIFY_SUBSCRIPTION_READY
}
